### ISSUE TITLE
Try to write more concise code

### ISSUE THREAD

**Issue by baileypierson** [halalab/pwp-capstones#2]
https://github.com/halalab/pwp-capstones/blob/80f34de4f8cccc62d9e8adcf08c6004f4bc9054b/Final%20project/Murder%2BMystery.ipynb#L208-L219

Again, this code ultimately works, but is rather difficult to read, I would write something like this:
```
def prepare_text(text):
    lower_text     = text.lower()
    punctuation    = ".,!?"
    no_punctuation = ''.join(letter for letter in lower_text if letter not in punctuation)
    return no_punctuation.split()
```

**Comment by halalab** [comment]
Thank you! Definitely a good one to learn from going forward! :-) 
I overlooked the fact that a string is a list, and didn't think of using a list comprehension ^^
