### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by baileypierson** [halalab/pwp-capstones#3]
### Criteria 1: Valid Python Code
* _Score Level:_  4/4
* _Comment(s):_ Everything actually runs!
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4/4
* _Comment(s):_ You touched on everything we asked for
 
### Criteria 3: Software Architecture
* _Score Level:_3/4
* _Comment(s):_While all your code ultimately worked, there were definitely some places where better structuring could have made your code more efficient
 
### Criteria 4: Uses Python Language Features
* _Score Level:_3/4
* _Comment(s):_More extensive use of python features, like list comprehensions, could hav e made your code easier to read

### Criteria 5: Produces Accurate Output
* _Score Level: 4/4
* _Comment(s): Congrats–– you found the true murderer!!

**Comment by halalab** [comment]
Thank you!
